/**
 * Regenerates route_polyline for every demo seed route by:
 *   1. Reading current start/end coords and stops from Supabase
 *   2. Calling Google Routes API for the real driving polyline
 *   3. Writing a SQL migration of UPDATE statements to stdout
 *
 * Usage:
 *   npx tsx -r dotenv/config scripts/regenerate-seed-polylines.ts dotenv_config_path=.env.local \
 *     > supabase/migrations/<timestamp>_fix_seed_polylines.sql
 */
import { createClient } from "@supabase/supabase-js";
import { getDirectionsPolyline, type LatLng } from "../lib/services/directions";

const SEED_ROUTE_IDS = [
  "a0000001-0000-0000-0000-000000000001",
  "a0000002-0000-0000-0000-000000000002",
  "a0000003-0000-0000-0000-000000000003",
  "a0000004-0000-0000-0000-000000000004",
  "a0000005-0000-0000-0000-000000000005",
  "a0000006-0000-0000-0000-000000000006",
  "a0000007-0000-0000-0000-000000000007",
  "a0000008-0000-0000-0000-000000000008",
  "a0000009-0000-0000-0000-000000000009",
  "a0000010-0000-0000-0000-000000000010",
];

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !key) throw new Error("Missing Supabase env vars");
  const supabase = createClient(url, key);

  const out: string[] = [
    "-- Regenerated route_polyline values via Google Routes API.",
    "-- Coords pulled from DB at generation time, so polylines match stored start/end/stops.",
    "-- Generated by scripts/regenerate-seed-polylines.ts",
    "",
  ];

  for (const id of SEED_ROUTE_IDS) {
    const { data: route, error } = await supabase
      .from("routes")
      .select("id, title, start_lat, start_lng, end_lat, end_lng, route_stops(order_index, latitude, longitude)")
      .eq("id", id)
      .maybeSingle();
    if (error) throw error;
    if (!route) {
      process.stderr.write(`Skipping ${id}: not in DB\n`);
      continue;
    }

    const start: LatLng = { lat: route.start_lat, lng: route.start_lng };
    const end: LatLng = { lat: route.end_lat, lng: route.end_lng };
    const stops: LatLng[] = (route.route_stops ?? [])
      .slice()
      .sort((a: { order_index: number }, b: { order_index: number }) => a.order_index - b.order_index)
      .map((s: { latitude: number; longitude: number }) => ({ lat: s.latitude, lng: s.longitude }));

    process.stderr.write(
      `Fetching ${id} (${route.title}) ${start.lat.toFixed(4)},${start.lng.toFixed(4)} → ${end.lat.toFixed(4)},${end.lng.toFixed(4)} (${stops.length} stops)… `,
    );
    const poly = await getDirectionsPolyline(start, end, stops);
    process.stderr.write(`${poly.length} chars\n`);
    out.push(
      `UPDATE routes SET route_polyline = '${sqlEscape(poly)}' WHERE id = '${id}';`,
    );
  }

  process.stdout.write(out.join("\n") + "\n");
}

main().catch((err) => {
  process.stderr.write(`ERROR: ${String(err)}\n`);
  process.exit(1);
});
